### ISSUE TITLE
file missing

### ISSUE THREAD

**Issue by asif-nuaa** [SalilVishnuKapur/Predicting-Transportation-Modes-of-GPS-Trajectories#1]
can you please upload full code with files especially geolife_raw.csv, so that it would be easier for us to understand and reuse your code. geolife data files in microsoft repository is in different structures.

**Comment by SalilVishnuKapur** [comment]
Yes I will update the repository, didn't upload geolife_raw.csv because of it's file size which is 238.2 Mb. Such large files are not supported by github. Though you will have everything in place by this weekend.

**Comment by SalilVishnuKapur** [comment]
Data file is available now. Also the project has been modularized.
