### ISSUE TITLE
Dataset?

### ISSUE THREAD

**Issue by ghost** [SalilVishnuKapur/Predicting-Transportation-Modes-of-GPS-Trajectories#2]
Can you plz upload the dataset ?

**Comment by SalilVishnuKapur** [comment]
Data file is available now. Also the project has been modularized.

**Comment by rbhatia46** [comment]
Hi,
how can I download the dataset file geolife_raw.csv using Git LFS?

**Comment by SalilVishnuKapur** [comment]
Hi Rahul,

Thanks for showing interest in the repository. I think you should be able
to, if not, then do let know I will share the data via some other way in
the repository.

**Comment by rbhatia46** [comment]
Actually I am not able to download it, it would be really helpful if you can share a publicly available download link(Dropbox or Google Drive), this is really interesting work, I would be highly obliged if you can provide a link to the dataset

**Comment by SalilVishnuKapur** [comment]
Oh, I think this might be because of the quota on LFS that github provides to repository owners. I will try to look into that but for now I will try to upload the data by EOD today probably using google drive. And thanks for appreciating the work.

**Comment by rbhatia46** [comment]
Hi @SalilVishnuKapur please upload the dataset whenever you find time.

**Comment by SalilVishnuKapur** [comment]
Dataset has been made available now, the link to it mentioned in the Readme file here (https://github.com/SalilVishnuKapur/Predicting-Transportation-Modes-of-GPS-Trajectories/blob/master/README.md). I hope this helps let me know otherwise. Thanks again for letting me know about this issue.
