### ISSUE TITLE
Source for geolife_raw.csv

### ISSUE THREAD

**Issue by SoumiDas** [SalilVishnuKapur/Predicting-Transportation-Modes-of-GPS-Trajectories#3]
Hi,

I am new to this dataset. I came across the official repo for downloading the entire data, but then I didn't receive any geolife_raw.csv file like the you used here. It's very detailed and all transportation modes are available too alongside with GPS loggers. Can you please help me to know how did you create this geolife_raw data or is it publicly available?

Thanks!

**Comment by SalilVishnuKapur** [comment]
I can check with my fellow researchers at my lab. Actually it was provided by them. I will get back to you soon.

**Comment by SoumiDas** [comment]
Hi,
Thanks for the response. Can you please let me know soon. It'll be really helpful! :)

Regards,

**Comment by SalilVishnuKapur** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=52367

Let me know if it helped.

**Comment by SalilVishnuKapur** [comment]
Closing this now.
